"""
Adapter around datamodel-code-generator (DCG).

``DcgModelRenderer`` turns a set of named IR schemas into the source of a ``models/`` package and
reports where each model landed. The options below are fixed on purpose: they are what make DCG's
output match what the endpoint generators and the cattrs runtime expect.
"""

from __future__ import annotations

import json
import logging
import tempfile
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from datamodel_code_generator import (
    GeneratedModules,
    InputFileType,
    ModuleSplitMode,
    OpenAPIScope,
    generate,
)
from datamodel_code_generator.enums import DataModelType
from datamodel_code_generator.format import DatetimeClassType, Formatter, PythonVersion

from pyopenapi_gen.generator.exceptions import GenerationError
from pyopenapi_gen.ir import IRSchema

from .ir_to_openapi import IRSchemaSerializer, SerializedModels

logger = logging.getLogger(__name__)

_TEMPLATE_DIR = Path(__file__).parent / "templates"
_FILE_HEADER = "# Generated by pyopenapi-gen using datamodel-code-generator. Do not edit."
_PACKAGE_INIT = "__init__.py"


@dataclass(frozen=True)
class ModelLocation:
    """Where DCG put one model."""

    module_stem: str
    class_name: str


@dataclass(frozen=True)
class RenderedModels:
    """The files for a ``models/`` package (without ``__init__.py``) and the location of every requested model."""

    files: dict[str, str]
    """Relative file name -> Python source."""

    locations: dict[str, ModelLocation]
    """Requested ``generation_name`` -> where that model was written."""

    anonymous_objects_flattened: int = 0


class DcgModelRenderer:
    """
    Renders IR schemas to Python models with datamodel-code-generator.

    Contracts:
        Preconditions:
            - every schema passed to ``render`` has a unique, non-empty ``generation_name``
        Postconditions:
            - ``locations`` has exactly one entry per requested schema, and each class is named
              exactly ``generation_name``
            - every attribute of every generated dataclass has the Python name the serializer chose,
              so the rendered ``Meta`` mappings are consistent with the class body
        Raises:
            GenerationError: when DCG renames a class or attribute, or omits a requested model
    """

    def render(self, schemas: Sequence[IRSchema]) -> RenderedModels:
        """
        Generate models for ``schemas``.

        Schemas that are referenced but not passed in are inlined at their use sites as plain types.
        """
        if not schemas:
            return RenderedModels(files={}, locations={})

        serialized = IRSchemaSerializer(schemas).serialize()
        modules, metadata = self._run_dcg(serialized)
        locations = self._locate_models(serialized, metadata)
        self._verify_field_names(serialized, metadata)

        files = {"/".join(path): source for path, source in modules.items() if path != (_PACKAGE_INIT,)}
        return RenderedModels(
            files=files, locations=locations, anonymous_objects_flattened=serialized.anonymous_objects_flattened
        )

    def _run_dcg(self, serialized: SerializedModels) -> tuple[GeneratedModules, list[dict[str, Any]]]:
        extra_template_data = {name: {"field_mappings": m} for name, m in serialized.field_mappings.items() if m}
        with tempfile.TemporaryDirectory() as scratch:
            metadata_path = Path(scratch) / "metadata.json"
            result = generate(
                serialized.document,
                input_file_type=InputFileType.OpenAPI,
                openapi_scopes=[OpenAPIScope.Schemas],
                output_model_type=DataModelType.DataclassesDataclass,
                # Emit 3.10-compatible syntax: `X: TypeAlias = A | B`, not a PEP 695 `type X = ...`
                # statement, which cattrs cannot see through when (un)structuring union members.
                target_python_version=PythonVersion.PY_310,
                use_type_alias=True,
                module_split_mode=ModuleSplitMode.Single,
                use_exact_imports=True,
                custom_class_name_generator=_keep_class_name,
                use_subclass_enum=True,
                use_specialized_enum=False,
                set_default_enum_member=True,
                output_datetime_class=DatetimeClassType.Datetime,
                custom_template_dir=_TEMPLATE_DIR,
                extra_template_data=extra_template_data,  # type: ignore[arg-type]
                formatters=[Formatter.BUILTIN],  # PostprocessManager formats the final files
                custom_file_header=_FILE_HEADER,
                disable_timestamp=True,
                emit_model_metadata=metadata_path,
            )
            metadata = json.loads(metadata_path.read_text(encoding="utf-8"))["models"]
        if not isinstance(result, dict):
            raise GenerationError("datamodel-code-generator returned a single module; expected one module per model.")
        return result, metadata

    @staticmethod
    def _definition_key(entry: dict[str, Any]) -> str | None:
        """The ``components.schemas`` key of a top-level model entry, or None for DCG-synthesised models."""
        path = entry.get("source_path") or []
        if len(path) == 3 and path[0] == "components" and path[1] == "schemas":
            return str(path[2])
        return None

    def _locate_models(self, serialized: SerializedModels, metadata: list[dict[str, Any]]) -> dict[str, ModelLocation]:
        by_key = {key: entry for entry in metadata if (key := self._definition_key(entry)) is not None}
        locations: dict[str, ModelLocation] = {}
        problems: list[str] = []
        for name in sorted(serialized.definitions):
            entry = by_key.get(name)
            if entry is None:
                problems.append(f"{name}: missing from datamodel-code-generator output")
            elif entry["class_name"] != name:
                problems.append(f"{name}: generated as class '{entry['class_name']}'")
            elif not entry["module"] or "." in entry["module"]:
                problems.append(f"{name}: unexpected module '{entry['module']}'")
            else:
                locations[name] = ModelLocation(module_stem=entry["module"], class_name=entry["class_name"])
        if problems:
            raise GenerationError(
                "datamodel-code-generator did not keep the IR's model names:\n  " + "\n  ".join(problems)
            )
        return locations

    def _verify_field_names(self, serialized: SerializedModels, metadata: list[dict[str, Any]]) -> None:
        problems: list[str] = []
        for entry in metadata:
            key = self._definition_key(entry)
            expected = serialized.field_names.get(key) if key is not None else None
            if expected is None:
                continue
            actual = [f["name"] for f in entry["fields"]]
            if actual != expected:
                problems.append(f"{key}: expected fields {expected}, generated {actual}")
        if problems:
            raise GenerationError("datamodel-code-generator changed attribute names:\n  " + "\n  ".join(problems))


def _keep_class_name(name: str) -> str:
    """DCG must not re-case names; the IR already holds final class names."""
    return name
