"""Tests for DcgModelRenderer: the adapter around datamodel-code-generator."""

from __future__ import annotations

import copy
from typing import Any

import pytest

from pyopenapi_gen import IRSchema
from pyopenapi_gen.emitters.dcg_models.renderer import DcgModelRenderer, ModelLocation
from pyopenapi_gen.generator.exceptions import GenerationError
from pyopenapi_gen.ir import ModelType


def _named(name: str, **kwargs: Any) -> IRSchema:
    return IRSchema(name=name, generation_name=name, **kwargs)


def _pet_and_status() -> list[IRSchema]:
    status = _named("PetStatus", type="string", enum=["available", "sold-out"])
    pet = _named(
        "Pet",
        type="object",
        required=["id", "status"],
        properties={
            "id": IRSchema(type="integer"),
            "status": status,
            "tags": IRSchema(type="array", items=IRSchema(type="string")),
            "createdAt": IRSchema(type="string", format="date-time"),
        },
    )
    return [pet, status]


def test_render__no_schemas__returns_empty_result_without_running_dcg() -> None:
    result = DcgModelRenderer().render([])

    assert result.files == {}
    assert result.locations == {}


def test_render__named_schemas__every_model_located_under_its_generation_name() -> None:
    # Given / When
    result = DcgModelRenderer().render(_pet_and_status())

    # Then one location per requested schema, class named exactly as requested
    assert set(result.locations) == {"Pet", "PetStatus"}
    assert all(loc.class_name == name for name, loc in result.locations.items())
    pet = result.locations["Pet"]
    assert isinstance(pet, ModelLocation)
    assert f"{pet.module_stem}.py" in result.files


def test_render__package_init_is_not_returned() -> None:
    # DCG's own __init__.py is dropped: ModelsEmitter writes the public one.
    result = DcgModelRenderer().render(_pet_and_status())

    assert "__init__.py" not in result.files


def test_render__generated_source__is_marked_as_generated_and_uses_python_attribute_names() -> None:
    result = DcgModelRenderer().render(_pet_and_status())

    source = result.files[f"{result.locations['Pet'].module_stem}.py"]
    assert source.startswith("# Generated by pyopenapi-gen")
    assert "created_at:" in source  # camelCase key renamed to a Python attribute
    assert "default_factory=list" in source  # optional array defaults to an empty list


def test_render__renamed_attribute__meta_maps_json_keys_to_python_names() -> None:
    result = DcgModelRenderer().render(_pet_and_status())

    source = result.files[f"{result.locations['Pet'].module_stem}.py"]
    assert "class Meta" in source
    assert "'createdAt': 'created_at'" in source or '"createdAt": "created_at"' in source


def test_render__enum__uses_str_enum_with_legacy_member_names() -> None:
    result = DcgModelRenderer().render(_pet_and_status())

    source = result.files[f"{result.locations['PetStatus'].module_stem}.py"]
    assert "class PetStatus(str, Enum)" in source
    assert "AVAILABLE" in source
    assert "SOLD_OUT" in source


def test_render__alias_schema__emitted_as_type_alias_not_pep695_statement() -> None:
    # PEP 695 ``type X = ...`` cannot be seen through by cattrs, so the old-style alias is required.
    alias = _named("Ids", type="array", items=IRSchema(type="integer"))

    result = DcgModelRenderer().render([alias])

    source = result.files[f"{result.locations['Ids'].module_stem}.py"]
    assert "Ids: TypeAlias = list[int]" in source
    assert "\ntype Ids" not in source


class TestPreset:
    @pytest.mark.parametrize("preset", ["standard-py310-20260909", "practical-py310-20260909"])
    def test_render__py310_preset__same_locations_and_pep484_alias(self, preset: str) -> None:
        """
        Scenario:
            A Python 3.10 preset is forwarded to DCG.

        Expected Outcome:
            Every model keeps its requested name and aliases are still ``TypeAlias`` assignments.
        """
        alias = _named("Ids", type="array", items=IRSchema(type="integer"))

        result = DcgModelRenderer(preset=preset).render(_pet_and_status() + [alias])

        assert set(result.locations) == {"Pet", "PetStatus", "Ids"}
        assert "Ids: TypeAlias = list[int]" in result.files[f"{result.locations['Ids'].module_stem}.py"]

    def test_render__py312_preset__target_version_comes_from_preset_and_warns(
        self, caplog: pytest.LogCaptureFixture
    ) -> None:
        """
        Scenario:
            A Python 3.12 preset is used; the renderer must not pin its own 3.10 target (DCG would reject it).

        Expected Outcome:
            Generation succeeds, aliases use PEP 695 ``type`` statements, and a warning is logged.
        """
        alias = _named("Ids", type="array", items=IRSchema(type="integer"))

        with caplog.at_level("WARNING"):
            result = DcgModelRenderer(preset="standard-py312-20260909").render([alias])

        assert "type Ids = list[int]" in result.files[f"{result.locations['Ids'].module_stem}.py"]
        assert "PEP 695" in caplog.text

    def test_init__unknown_preset__raises_generation_error(self) -> None:
        """
        Scenario:
            The renderer is built with a preset name DCG does not know.

        Expected Outcome:
            A GenerationError listing the valid names.
        """
        with pytest.raises(GenerationError, match="Unknown datamodel-code-generator preset 'nope'"):
            DcgModelRenderer(preset="nope")

    def test_render__preset__fixed_options_still_win(self) -> None:
        """
        Scenario:
            A preset that sets options the renderer fixes (formatting, headers) is applied.

        Expected Outcome:
            The generated-file header and dataclass output are unchanged.
        """
        result = DcgModelRenderer(preset="practical-py310-20260909").render(_pet_and_status())

        source = result.files[f"{result.locations['Pet'].module_stem}.py"]
        assert source.startswith("# Generated by pyopenapi-gen")
        assert "@dataclass" in source


class TestPydanticModels:
    @staticmethod
    def _render() -> tuple[dict[str, str], dict[str, Any]]:
        result = DcgModelRenderer(ModelType.PYDANTIC).render(_pet_and_status())
        return result.files, result.locations

    def test_render__pydantic__object_is_base_model_with_python_names_and_wire_aliases(self) -> None:
        files, locations = self._render()

        source = files[f"{locations['Pet'].module_stem}.py"]
        assert "class Pet(BaseModel)" in source
        assert "@dataclass" not in source
        assert "populate_by_name=True" in source  # callers can construct with Python names
        assert "created_at:" in source
        assert "alias='createdAt'" in source or 'alias="createdAt"' in source

    def test_render__pydantic__same_locations_as_dataclass(self) -> None:
        _, pydantic_locations = self._render()

        dataclass_locations = DcgModelRenderer().render(_pet_and_status()).locations

        assert pydantic_locations == dataclass_locations

    def test_render__pydantic__optional_array_is_plain_list_with_empty_default(self) -> None:
        files, locations = self._render()

        assert "tags: list[str] = []" in files[f"{locations['Pet'].module_stem}.py"]

    def test_render__pydantic__enum_keeps_legacy_member_names(self) -> None:
        files, locations = self._render()

        source = files[f"{locations['PetStatus'].module_stem}.py"]
        assert "class PetStatus(str, Enum)" in source
        assert "SOLD_OUT" in source

    def test_render__pydantic__no_dataclass_meta_block(self) -> None:
        files, locations = self._render()

        assert "class Meta" not in files[f"{locations['Pet'].module_stem}.py"]

    def test_render__pydantic_attribute_renamed_by_dcg__generation_fails_loudly(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # Given DCG reporting a different attribute name than the serializer chose
        original = DcgModelRenderer._run_dcg

        def patched(self: DcgModelRenderer, serialized: Any) -> Any:
            modules, metadata = original(self, serialized)
            metadata = copy.deepcopy(metadata)
            next(m for m in metadata if m["class_name"] == "Pet")["fields"][0]["name"] = "renamed"
            return modules, metadata

        monkeypatch.setattr(DcgModelRenderer, "_run_dcg", patched)

        with pytest.raises(GenerationError, match="changed attribute names"):
            DcgModelRenderer(ModelType.PYDANTIC).render(_pet_and_status())


class TestContractViolations:
    """DCG must never silently rename what the endpoint generators import."""

    @staticmethod
    def _patch_metadata(monkeypatch: pytest.MonkeyPatch, mutate: Any) -> None:
        original = DcgModelRenderer._run_dcg

        def patched(self: DcgModelRenderer, serialized: Any) -> Any:
            modules, metadata = original(self, serialized)
            metadata = copy.deepcopy(metadata)
            mutate(metadata)
            return modules, metadata

        monkeypatch.setattr(DcgModelRenderer, "_run_dcg", patched)

    def test_dcg_renames_a_class__generation_fails_loudly(self, monkeypatch: pytest.MonkeyPatch) -> None:
        def rename(metadata: list[dict[str, Any]]) -> None:
            for entry in metadata:
                if entry["class_name"] == "Pet":
                    entry["class_name"] = "Pet1"

        self._patch_metadata(monkeypatch, rename)

        with pytest.raises(GenerationError, match="generated as class 'Pet1'"):
            DcgModelRenderer().render(_pet_and_status())

    def test_dcg_omits_a_model__generation_fails_loudly(self, monkeypatch: pytest.MonkeyPatch) -> None:
        self._patch_metadata(
            monkeypatch,
            lambda metadata: metadata.__setitem__(slice(None), [m for m in metadata if m["class_name"] != "Pet"]),
        )

        with pytest.raises(GenerationError, match="Pet: missing from datamodel-code-generator output"):
            DcgModelRenderer().render(_pet_and_status())

    def test_dcg_places_a_model_in_a_submodule__generation_fails_loudly(self, monkeypatch: pytest.MonkeyPatch) -> None:
        def nest(metadata: list[dict[str, Any]]) -> None:
            for entry in metadata:
                if entry["class_name"] == "Pet":
                    entry["module"] = "a.b"

        self._patch_metadata(monkeypatch, nest)

        with pytest.raises(GenerationError, match="unexpected module"):
            DcgModelRenderer().render(_pet_and_status())

    def test_dcg_changes_an_attribute_name__generation_fails_loudly(self, monkeypatch: pytest.MonkeyPatch) -> None:
        def rename_field(metadata: list[dict[str, Any]]) -> None:
            for entry in metadata:
                if entry["class_name"] == "Pet":
                    entry["fields"][0]["name"] = "renamed"

        self._patch_metadata(monkeypatch, rename_field)

        with pytest.raises(GenerationError, match="changed attribute names"):
            DcgModelRenderer().render(_pet_and_status())
